name: Error numbers
on:
  pull_request:
    paths:
      - '.github/workflows/errno.yml'
      - 'lib/libc/minimal/include/errno.h'
      - 'scripts/ci/errno.py'
      - 'SDK_VERSION'

permissions:
  contents: read

jobs:
  check-errno:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.28.4

    steps:
      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Environment Setup
        run: |
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )" >> $GITHUB_ENV

      - name: Run errno.py
        run: |
          export ZEPHYR_BASE=${PWD}
          ./scripts/ci/errno.py
